services:
    combobox:
        image: ghcr.io/prvious/frankenphp:latest-dev
        volumes:
            - ./:/app
            - ./php.ini:/usr/local/etc/php/php.ini:ro
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.combobox.rule=Host(`combobox.test`)
            - traefik.http.services.combobox.loadbalancer.server.port=80
            - traefik.http.routers.combobox.entrypoints=http,https
            - "traefik.http.routers.combobox.service=combobox"
            # - traefik.http.routers.combobox.tls=true

            - "traefik.http.services.vite.loadbalancer.server.port=5173"
            - "traefik.http.routers.vite.rule=Host(`vite.combobox.test`)"
            - "traefik.http.routers.vite.entrypoints=http,https"
            - "traefik.http.routers.vite.service=vite"
            # - "traefik.http.routers.vite.tls=true"

            - prvious.ssl.enable=true
            - prvious.ssl.domains=combobox.test,vite.combobox.test
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/up"]
            interval: 10s
            retries: 5
            timeout: 5s

networks:
    traefik:
        external: true
